<?php
return [
    'skip' => 'Zum Inhalt springen',
    'nav.home' => 'Start',
    'nav.menu' => 'Speisekarte',
    'nav.contact' => 'Kontakt',
    'nav.reserve' => 'Reservieren',
    'nav.toggle' => 'Menü öffnen',
    'nav.main' => 'Hauptnavigation',
    'lang.label' => 'Sprache',

    'hero.eyebrow' => 'Moin! Mitten in der Altstadt von Stralsund',
    'hero.title' => 'Brunch & Tapas Heaven N°1',
    'hero.lead' => 'Frisch gekocht und gebacken, mit Zutaten aus Vorpommern und von Rügen. Morgens Frühstück, abends Tapas.',
    'cta.menu' => 'Zur Speisekarte',
    'cta.reserve' => 'Tisch reservieren',
    'cta.contact' => 'Kontakt & Anfahrt',
    'cta.maps' => 'Route in Google Maps',

    'status.open' => 'Jetzt geöffnet',
    'status.closed' => 'Gerade geschlossen',
    'status.today' => 'Heute {time} Uhr',
    'status.closed_today' => 'Heute geschlossen',

    'home.duo.eyebrow' => 'Morgens & abends',
    'home.duo.title' => 'Zwei Seiten, eine Küche',
    'home.brunch.title' => 'Frühstück & Brunch',
    'home.brunch.text' => 'Vom kleinen Frühstück zum Start in den Tag bis zum großen Brunch, für den du dir Zeit nimmst.',
    'home.tapas.title' => 'Tapas am Abend',
    'home.tapas.text' => 'Saisonale Tapas aus dem, was Vorpommern und Rügen gerade hergeben. Jeden Tag ein bisschen anders.',

    'home.values.eyebrow' => 'Was uns wichtig ist',
    'home.values.title' => 'Einfach gutes Essen.',
    'value.fresh.title' => 'Frisch gemacht',
    'value.fresh.text' => 'Wir kochen und backen selbst, aus frischen Zutaten.',
    'value.regional.title' => 'Aus der Region',
    'value.regional.text' => 'Unsere Rohstoffe kommen täglich aus Vorpommern und von Rügen.',
    'value.vegan.title' => 'Vegan willkommen',
    'value.vegan.text' => 'Egal ob vegan oder mit Fleisch: Bei uns wird jeder richtig satt.',
    'value.gf.title' => 'Glutenfrei möglich',
    'value.gf.text' => 'Rund 80 % unserer Karte bereiten wir auf Nachfrage glutenfrei zu.',

    'home.visit.eyebrow' => 'Besuch uns',
    'home.visit.title' => 'Komm vorbei',
    'home.visit.text' => 'Du findest uns in der Badenstraße, mitten in der Stralsunder Altstadt.',

    'hours.title' => 'Öffnungszeiten',
    'hours.closed' => 'geschlossen',
    'hours.suffix' => 'Uhr',
    'hours.missing' => 'Unsere aktuellen Öffnungszeiten stehen hier in Kürze.',

    'day.mon' => 'Montag', 'day.tue' => 'Dienstag', 'day.wed' => 'Mittwoch', 'day.thu' => 'Donnerstag',
    'day.fri' => 'Freitag', 'day.sat' => 'Samstag', 'day.sun' => 'Sonntag',
    'day.short.mon' => 'Mo', 'day.short.tue' => 'Di', 'day.short.wed' => 'Mi', 'day.short.thu' => 'Do',
    'day.short.fri' => 'Fr', 'day.short.sat' => 'Sa', 'day.short.sun' => 'So',

    'menu.title' => 'Speisekarte',
    'menu.lead' => 'Frühstück, Brunch und Tapas. Frag uns gern nach veganen und glutenfreien Varianten.',
    'menu.jump' => 'Kategorien',
    'menu.empty.title' => 'Unsere Karte bekommt gerade ein Update',
    'menu.empty.text' => 'Schau bald wieder vorbei oder ruf uns an, wir erzählen dir gern, was es heute gibt.',
    'menu.legend' => 'Kennzeichnung',
    'menu.allergens' => 'Fragen zu Allergenen und Zusatzstoffen? Sprich uns an, wir helfen dir gern weiter.',
    'menu.prices' => 'Alle Preise in Euro inklusive Mehrwertsteuer.',
    'tag.vegan' => 'vegan',
    'tag.vegetarian' => 'vegetarisch',
    'tag.glutenfree' => 'glutenfrei möglich',
    'tag.lactosefree' => 'laktosefrei möglich',
    'tag.new' => 'neu',

    'contact.title' => 'Kontakt & Anfahrt',
    'contact.lead' => 'Fragen, Gruppen oder einfach nur Hunger? Ruf an, schreib uns oder komm direkt vorbei.',
    'contact.address' => 'Adresse',
    'contact.phone' => 'Telefon',
    'contact.email' => 'E-Mail',
    'contact.instagram' => 'Instagram',
    'contact.reach' => 'So erreichst du uns',
    'contact.directions' => 'Anfahrt',
    'contact.map_alt' => 'Karte der Stralsunder Altstadt mit dem Standort von Konvergenz 53',
    'contact.map_open' => 'In Google Maps öffnen',
    'contact.map_hint' => 'Öffnet Google Maps in einem neuen Tab.',
    'directions.default' => "Wir liegen in der Badenstraße mitten in der Stralsunder Altstadt, nur wenige Gehminuten vom Alten Markt entfernt.\nMit dem Auto parkst du am besten auf einem der Parkplätze rund um die Altstadt und gehst die letzten Meter zu Fuß.",
    'reserve.text' => 'Du möchtest einen Tisch? Reserviere bequem online.',

    'footer.tagline' => 'Brunch & Tapas in der Altstadt von Stralsund.',
    'footer.legal' => 'Rechtliches',
    'footer.follow' => 'Folge uns',
    'imprint.title' => 'Impressum',
    'privacy.title' => 'Datenschutz',
    'legal.de_only' => '',

    'notfound.title' => 'Diese Seite gibt es nicht (mehr)',
    'notfound.text' => 'Vielleicht hat sich die Adresse geändert. Hier geht es weiter:',
    'notfound.home' => 'Zur Startseite',

    'meta.home' => 'Konvergenz 53 in der Altstadt von Stralsund: Frühstück, Brunch und saisonale Tapas aus frischen, regionalen Zutaten. Vegan und glutenfrei möglich.',
    'meta.menu' => 'Die Speisekarte von Konvergenz 53 in Stralsund: Frühstück, Brunch und Tapas, vieles vegan und glutenfrei möglich.',
    'meta.contact' => 'Adresse, Telefon, Öffnungszeiten und Anfahrt zu Konvergenz 53, Badenstraße 53 in Stralsund.',
    'meta.legal' => 'Rechtliche Angaben zu Konvergenz 53, Stralsund.',
    'notice.label' => 'Hinweis',
];
